DROP TABLE IF EXISTS cards;

CREATE TABLE cards (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject VARCHAR(50),
    description VARCHAR(250)
);

INSERT INTO cards VALUES('TESTE', 'TESTEKJCASJCBA');
INSERT INTO cards VALUES('TESTE2', 'TESTEKJCA2222');
