management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
